version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  app:
    build: .
    volumes:
      - .:/django
    
    ports:
      - "8000:8000"
    container_name: django_container
    image: app:django
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    env_file:
      - .env

  script:
    build: .
    command: python3 data.proc.py
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data: