FROM python:3.8-buster

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1


WORKDIR /django

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .

COPY . /google_patent/
RUN python3 data.proc.py

CMD python3 manage.py runserver 0.0.0.0:8000
